[package]
name = "tor-hash-passwd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sha1 = "=0.6.0"
hex-literal = "0.3.4"
hex = "0.4.3"