---
name: CI

'on':
  push:
    branches:
      - main
      - "ci-*"
  pull_request:
    types:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:
  workflow_dispatch:

env:
  CARGO_HTTP_MULTIPLEXING: false
  toolchain: nightly-2021-11-01

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}
          components: clippy, rustfmt

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ runner.cpu-model }}-${{ env.toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            libssl-dev \
            openssl \
            pkg-config \
            git

      - name: cargo format
        run: cargo fmt --all -- --check

      - name: Install cargo-lints
        run: cargo install cargo-lints

      - name: Clippy check (with lints)
        run: cargo lints clippy --all-targets -- -D warnings

      - name: cargo machete
        run: |
          cargo install cargo-machete
          cargo machete

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ runner.cpu-model }}-${{ env.toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            libssl-dev \
            openssl \
            git \
            cmake \
            zip

      - name: cargo test
        run: cargo test

      - name: cargo test release
        run: cargo test --release
